### ISSUE TITLE
Problem installing nh_plus on nix-darwin

### ISSUE THREAD

**Issue by mettavi** [ToyVo/nh_plus#25]
Hi, I just installed the current beta . It installed ok, but when running `nh os switch` I am getting this error:

```
error: flake 'git+file:///Users/timotheos/.dotfiles?dir=nix-darwin' does not provide
attribute 'packages.x86_64-darwin.nixosConfigurations."MVs-MBP.local".config.system.build.toplevel', 
'legacyPackages.x86_64-darwin.nixosConfigurations."MVs-MBP.local".config.system.build.toplevel' 
or 'nixosConfigurations."MVs-MBP.local".config.system.build.toplevel'
```

In my flake.nix I have  added:

```
nh_plus.url = "github:ToyVo/nh_plus";
```
And in configuration.nix:

```
nhpkgs = inputs.nh_plus.packages.${system}.nh;
...
environment.systemPackages = with pkgs; [
nhpkgs
];
```

So, I am wondering why the error message is mentioning `nixosConfigurations` which doesn't exist on my system, as I am running nix-darwin? I have `darwinConfigurations` instead.

Any help would be welcome. 😊

**Comment by ToyVo** [comment]
I suggest using the latest tag. This fork is winding down since upstream now supports nix-darwin. The only feature I have yet to get into upstream is git pull.

**Comment by mettavi** [comment]
Thanks for the reply.

For anyone else with the same problem, I have found out that there is a new subcommand for nh when used on nix-darwin, `nh darwin switch`.

When I ran that from this repo it complained about a missing input to the parent repo at `github.com/viperML/nh`.

So I reinstalled the package from the parent repo  and now `nh darwin switch` works. 👍
